### ISSUE TITLE
Launcher issue

### ISSUE THREAD

**Issue by fsnikb** [xertxa/Zyklon#12]
Nothing happens when i click Load, its stays the same 
I have followed the setup guide
[](https://imgur.com/a/87SgkQy)

**Comment by fsnikb** [comment]
![1](https://user-images.githubusercontent.com/65249643/81731355-b3b91080-9486-11ea-8d10-52ae680f4cb9.png)
![2](https://user-images.githubusercontent.com/65249643/81731358-b451a700-9486-11ea-9731-e247708ccb0c.png)

**Comment by xertxa** [comment]
your JAVA_HOME variable most likely isnt set correctly. change 60 to 251 instead, or whatever number it says in C:\Program Files\Java.

**Comment by fsnikb** [comment]
Ok will try, i’ll let you know when or if fixed.

**Comment by fsnikb** [comment]
Yes that has fixed it, thank you
