### ISSUE TITLE
Cant get it to work

### ISSUE THREAD

**Issue by Pallemaster1400** [xertxa/Zyklon#24]
Okay so when i launch the injector,jar file nothing happens. 

Then i write in cmd. java -jar injector.jar and get this https://gyazo.com/498592606a6d0ec036c239a0ffc0cb65

Then i click done and get this https://gyazo.com/6b823fb22c6856ae9ab3088f5036e9a0

Then when i go to the localhost:1337 i opens the config page but nothing will work ingame

What am i doing wrong?

**Comment by xertxa** [comment]
keep the cloud configuration server window open and open up the injector again, it should connect this time

another window will be opened with an error saying that the port is already in use, just close that

**Comment by Pallemaster1400** [comment]
okay i just tried that, and when i click load i get this in the cmd
https://gyazo.com/ce9fcd18dbd94bef772439d186d79b00
@xertxa

**Comment by xertxa** [comment]
your jdk wasnt setup correctly. can you show me the path you set in your environment variable as well as what it looks like in the path itself?

**Comment by Pallemaster1400** [comment]
this is the path and environment variable https://gyazo.com/e3abae4c515584c146528f34d0580905

**Comment by Pallemaster1400** [comment]
okay i found the issue, i made a mistake and downloaded Java SE 14 and not Java SE 8u251. so far so good, now it just keep on giving me an warning to make sure you have minecraft forge 1.7.10/1.8.9 running, even when im on either 1.7.10 forge or 1.8.9 forge

**Comment by xertxa** [comment]
1.8.9-forge1.8.9-11.15.1.1722 might be outdated. try using a more up to date version instead

if that doesnt work, try running the injector as admin. you can do this by running cmd as admin, cding into bin and do java -jar injector.jar

**Comment by Pallemaster1400** [comment]
i got it to work on 1.7.10-Forge10.13.4.1558-1.7.10 and on 1.8.9-forge1.8.9-11.15.1.2318.1.8.9 

Thanks for your fast support @xertxa
