### ISSUE TITLE
How is the reach, calculated in the config? 

### ISSUE THREAD

**Issue by Pallemaster1400** [xertxa/Zyklon#25]
So as the title says, how is the reach calculated since it goes from 0.00 to 1 and not like 1-6 block

**Comment by NDSDNS** [comment]
From 3 blocks to 4 blocks?

**Comment by Pallemaster1400** [comment]
then thing i mean is where is it 3 block and where is it 4 block here ? https://gyazo.com/333b33eac1a6d9961ed90a7ae931ea29

**Comment by NDSDNS** [comment]
It is amount of reach to add. Vanilla is 3 blocks. if you add 1, it makes 4 blocks. Try using more than 0.1 braincells next time

**Comment by Pallemaster1400** [comment]
wow toxic man here
